[build]
  functions = "netlify/functions"
  command = "npm run build"  # Or "echo 'No build needed'" if no frontend


[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["express", "cookie-parser", "dotenv", "mongoose" ] # add all your dependencies here

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true
  headers = { Access-Control-Allow-Origin = "*", Access-Control-Allow-Headers = "Authorization, Content-Type, Accept", Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS" }


[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://mern-ecommerce-website-store.netlify.app, http://localhost:5173"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Credentials = "true"
